# Generated by Django 3.1.2 on 2020-11-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('password', models.CharField(max_length=20)),
                ('aadharnumber', models.DecimalField(decimal_places=0, max_digits=12)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
