# Generated by Django 3.1.2 on 2020-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmsmod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bloodpressure', models.CharField(max_length=7)),
                ('bloodgroup', models.CharField(max_length=3)),
                ('past_disease', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
            ],
        ),
    ]
